
CREATE TABLE UserTypes (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Name VARCHAR(50) NOT NULL UNIQUE
)

INSERT INTO UserTypes (Id, Name) VALUES
(NEWID(), 'Client'),
(NEWID(), 'Administrator'),
(NEWID(), 'Attendant'),
(NEWID(), 'Manager')

CREATE TABLE Users (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserTypeId UNIQUEIDENTIFIER NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Phone VARCHAR(11),
    CPF VARCHAR(11) UNIQUE,
    Passport VARCHAR(8) UNIQUE,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    FOREIGN KEY (UserTypeId) REFERENCES UserTypes(Id)
)

CREATE TABLE TravelPackages (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Title VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Destination VARCHAR(100) NOT NULL,
    Duration VARCHAR(50),
    BasePrice DECIMAL(10, 2) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    IsActive BIT NOT NULL DEFAULT 1
)

CREATE TABLE WishList (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    UserId UNIQUEIDENTIFIER NOT NULL,
    PackageId UNIQUEIDENTIFIER NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (PackageId) REFERENCES TravelPackages(Id)
)

CREATE TABLE PackageDateRanges (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PackageId UNIQUEIDENTIFIER NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    IsAvailable BIT NOT NULL DEFAULT 1,
    FOREIGN KEY (PackageId) REFERENCES TravelPackages(Id)
)

CREATE TABLE PackageMedia (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PackageId UNIQUEIDENTIFIER NOT NULL,
    MediaType VARCHAR(20) NOT NULL,
    FileName VARCHAR(255) NOT NULL,
    Url VARCHAR(255) NOT NULL,
    FOREIGN KEY (PackageId) REFERENCES TravelPackages(Id)
)

CREATE TABLE Reservations (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PackageId UNIQUEIDENTIFIER NOT NULL,
    PackageDateRangeId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    ReservationDate DATETIME NOT NULL DEFAULT GETDATE(),
    NumTravelers INT NOT NULL,
    Status VARCHAR(50) NOT NULL DEFAULT 'pending',
    TotalAmount DECIMAL(10, 2) NOT NULL,
    ReservationCode VARCHAR(20) NOT NULL UNIQUE,
    FOREIGN KEY (PackageId) REFERENCES TravelPackages(Id),
    FOREIGN KEY (PackageDateRangeId) REFERENCES PackageDateRanges(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
)

CREATE TABLE PaymentMethods (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Type VARCHAR(50) NOT NULL UNIQUE
)

CREATE TABLE Discounts (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    Code VARCHAR(10) UNIQUE,
    Description VARCHAR(255) NOT NULL,
    Percentage INT NOT NULL,
    ValidFrom DATE NOT NULL,
    ValidUntil DATE NOT NULL,
    IsActive BIT NOT NULL DEFAULT 1
)

CREATE TABLE Payments (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    ReservationId UNIQUEIDENTIFIER NOT NULL,
    PaymentMethodId UNIQUEIDENTIFIER NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    PaymentDate DATETIME NOT NULL DEFAULT GETDATE(),
    Status VARCHAR(50) NOT NULL DEFAULT 'pending',
    DiscountAppliedId UNIQUEIDENTIFIER,
    FOREIGN KEY (ReservationId) REFERENCES Reservations(Id),
    FOREIGN KEY (PaymentMethodId) REFERENCES PaymentMethods(Id),
    FOREIGN KEY (DiscountAppliedId) REFERENCES Discounts(Id)
)

CREATE TABLE Reviews (
    Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
    PackageId UNIQUEIDENTIFIER NOT NULL,
    UserId UNIQUEIDENTIFIER NOT NULL,
    Rating INT NOT NULL,
    Comment TEXT,
    ReviewDate DATETIME NOT NULL DEFAULT GETDATE(),
    IsApproved BIT NOT NULL DEFAULT 0,
    FOREIGN KEY (PackageId) REFERENCES TravelPackages(Id),
    FOREIGN KEY (UserId) REFERENCES Users(Id)
)
